# Generated by Django 4.0.4 on 2022-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_creation_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('inputA', models.IntegerField()),
                ('inputB', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('subtraction', models.IntegerField()),
                ('multiplication', models.IntegerField()),
                ('division', models.FloatField()),
            ],
        ),
    ]
